### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by khieta** [inQWIRE/QuantumLib#10]
It would be *awesome* to have continuous integration running to check that QuantumLib compiles with different versions of Coq. (Last I checked, QuantumLib should work with v8.12-8.14.) Note that coq-community does this for CoRN (https://github.com/coq-community/corn) -- maybe we could get QuantumLib into coq-community?

Some useful links for Coq CI:
* https://coq-workshop.gitlab.io/2020/abstracts/Coq2020_02-02-docker.pdf
* https://github.com/coq-community/templates
* https://github.com/erikmd/docker-coq-github-action-demo

**Comment by khieta** [comment]
Assigned myself & @k4rtik to this issue... between the two of us we should be able to figure it out.

**Comment by k4rtik** [comment]
Hi @khieta, my PR seems to be correctly running the CI. I didn't add an opam file, but that can be done too if needed.

Please take a look when you can.

cc'ing @rnrand to let him know that CI is ready in #15.
