### ISSUE TITLE
LGPL violation

### ISSUE THREAD

**Issue by fvoichick** [inQWIRE/QuantumLib#21]
According to the [GNU LGPL](https://www.gnu.org/licenses/lgpl-3.0.en.html):

> If you modify a copy of the Library, and, in your modifications, a
facility refers to a function or data to be supplied by an Application
that uses the facility (other than as an argument passed when the
facility is invoked), then you may convey a copy of the modified
version:
> -   a) under this License, provided that you make a good faith effort
    to ensure that, in the event an Application does not supply the
    function or data, the facility still operates, and performs
    whatever part of its purpose remains meaningful, or
> -   b) under the GNU GPL, with none of the additional permissions of
    this License applicable to that copy.

Coquelicot is distributed under the LGPL, so this project should be as well.

**Comment by rnrand** [comment]
This is not a modification of Coquelicot. It is a library that relies upon one file from Coquelicot, and that file remains under the LGPL. 

The QWIRE license explicitly says 

> This license does not apply to the file Complex.v, which is modified from the Coquelicot project and remains under the GNU Lesser General Public License.

I can add that to this project too.
