### ISSUE TITLE
How to use dune? 

### ISSUE THREAD

**Issue by jakezweifler** [inQWIRE/QuantumLib#22]
Not exactly an issue, but it would be good to have some sort of guide to teach people who are new to dune how to use the library with dune correctly. Specifically,  I am unsure of how to use QuantumLib with other projects. Currently, I have been cloning QuantumLib and just adding files to the QuantumLib folder which is clearly incorrect. My understanding is that there is some way of compiling QuantumLib so that it is automatically added to the list of potential libraries, but I am unsure of how to do this. I am also unsure of how this would work with git since currently submodules are used. This would be quite helpful since we can once and for all check compatibility of QWIRE, SQIR, etc... with QuantumLib and can remove the many redundancies across the projects.

**Comment by khieta** [comment]
You should be able to install QuantumLib as a library using the opam package manager. I believe this is as simple as running `opam pin coq-quantumlib https://github.com/inQWIRE/QuantumLib.git`. This should allow you to import QuantumLib files into other Coq files.

Try that out, and if it works then add it to the README.

**Comment by jakezweifler** [comment]
> Thanks for the quick reply! I tried this and it seems to install the library, but I still get an error when I try to import/export QuantumLib files (for eg. Require Import Matrix). Looking in my directories in the coq library, it seems that there is a folder called coq and a folder called coq-quantumlib, so perhaps I need a slightly altered import statement? But I can't find any examples or answers online.

**Comment by khieta** [comment]
Did you try `Require Import QuantumLib.Matrix.`? This seems to work on my machine.
