### ISSUE TITLE
Publish opam package

### ISSUE THREAD

**Issue by khieta** [inQWIRE/QuantumLib#26]
Once all admits are filled in & documentation is complete; submit coq-quantumlib to the official Coq opam respository following the directions [here](https://coq.inria.fr/opam-packaging.html).

Also worth considering: submit the project to [coq-community](https://coq-community.org/) so that it can be properly maintained.

**Comment by khieta** [comment]
The only admitted lemma is `pad_ctrl_ctrl_commutes` in Pad.v. The proof can be completed with `gridify` but it's horribly slow, so it's commented out now. We could try to fix `gridify` or just do the proof manually.

**Comment by k4rtik** [comment]
I agree with Jake.

I think whenever we do a version upgrade on the repo, a new package should be submitted to opam as well.

**Comment by khieta** [comment]
I updated SQIR to work with the latest version of QuantumLib & did a little bit of cleanup -- so you should be good to submit to the official opam repo now.

@jakezweifler @k4rtik

**Comment by k4rtik** [comment]
<img width="981" alt="Screen Shot 2022-08-02 at 8 37 31 AM" src="https://user-images.githubusercontent.com/374340/182388381-e2a7f039-7641-4ce0-af2b-749903444fdb.png">
