### ISSUE TITLE
Opam package

### ISSUE THREAD

**Issue by khieta** [inQWIRE/QuantumLib#8]
Make QuantumLib into an opam package. Useful links:
* https://opam.ocaml.org/doc/Packaging.html
* https://coq.inria.fr/opam-packaging.html

**Comment by k4rtik** [comment]
Now that #15 is merged, if someone adds an opam file, we should update the C config to use that.

The most helpful doc is at https://github.com/coq-community/docker-coq-action/blob/master/README.md
